# Generated by Django 5.1.1 on 2024-11-14 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_lugares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Festividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_festividad', models.CharField(max_length=100)),
                ('descripcion_festividad', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='TablalugaresV2',
        ),
        migrations.AddField(
            model_name='festividad',
            name='lugar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_lugares.lugar'),
        ),
        migrations.AddField(
            model_name='festividad',
            name='mes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_lugares.mes'),
        ),
    ]
