# Generated by Django 5.1.1 on 2024-10-14 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contraseña_hash', models.CharField(max_length=100)),
                ('region', models.CharField(choices=[('Junin', 'Junin'), ('Lima', 'Lima')], max_length=10)),
                ('correo_verificado', models.BooleanField(default=False)),
                ('token_verificacion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
