# Generated by Django 5.1.1 on 2024-11-15 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0003_alter_usuario_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='region',
            field=models.CharField(choices=[('Junin', 'Junin'), ('Lima', 'Lima')], max_length=10),
        ),
    ]
