# Generated by Django 5.1.1 on 2024-12-08 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0004_alter_usuario_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='region',
            field=models.CharField(max_length=100),
        ),
    ]
