# Generated by Django 5.1.1 on 2024-12-08 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0005_alter_usuario_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='region',
            new_name='lugar_procedencia',
        ),
    ]
