# Generated by Django 5.1.1 on 2024-12-11 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_users', '0006_rename_region_usuario_lugar_procedencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='api_users.usuario')),
            ],
            options={
                'db_table': 'preguntas',
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='api_root.pregunta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='api_users.usuario')),
            ],
            options={
                'db_table': 'respuestas',
            },
        ),
        migrations.CreateModel(
            name='Tripticos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateField()),
                ('fecha_retorno', models.DateField()),
                ('lugares_turisticos', models.TextField()),
                ('idioma', models.TextField()),
                ('hotel', models.TextField()),
                ('adultos', models.IntegerField()),
                ('infantes', models.IntegerField()),
                ('presupuesto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transporte', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('comidas', models.ManyToManyField(related_name='tripticos_comidas', to='api_root.respuesta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_users.usuario')),
            ],
            options={
                'db_table': 'tripticos',
            },
        ),
    ]
