# Generated by Django 5.1.1 on 2024-12-09 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_root', '0002_tripticos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripticos',
            name='respuestacomida',
        ),
        migrations.AddField(
            model_name='tripticos',
            name='comidas',
            field=models.ManyToManyField(related_name='tripticos_comidas', to='api_root.respuesta'),
        ),
    ]
